# -*- coding: utf-8 -*-
"""TEST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AaA6aSBrhQxBLoVuf_GB7YRwRs1n6YwF
"""

def main ():

   print ("NODE PYTHON CONNECT!")

if __name__ == "__main__":

   main ()